---

name: Lint Code Base

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true #https://github.com/github/super-linter/issues/143
          DEFAULT_BRANCH: master
          VALIDATE_DOCKER: true
          VALIDATE_GO: true
          VALIDATE_YAML: true